### PR TITLE
mysql driver added

### PR DESCRIPTION
**Pull request by shabane**
mysql driver added as all other driver format

### CODE REVIEW

**Comment by mghahari** [comment]
- Hostname and port should be included.
- Usage should be documented.

**Comment by mghahari** [comment]
It's not better to have a unique name for each credential of databases?
Using the same environment variable keys may cause some problems.

@sajad-sadra @shabane

**Comment by sajad-sadra** [comment]
i think if all of driver have a same variable name is better and cleaner for documentation

**Comment by sajad-sadra** [comment]
> It's not better to have a unique name for each credential of databases?
> Using the same environment variable keys may cause some problems.
> 
> @sajad-sadra @shabane

i think if all of driver have a same variable name is better and cleaner for documentation

**Comment by mghahari** [comment]
As each database has some specific configs it may break the integrity of the config names.
In addition, using a unique name for each config prevents some human errors.

**Comment by shabane** [comment]
> As each database has some specific configs it may break the integrity of the config names.
> In addition, using a unique name for each config prevents some human errors.

someone says if you don't like, leave this country(just kidding)

**Pull request merged**
